# Generated by Django 6.0.5 on 2026-07-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_per_stage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
