# Generated by Django 6.0.5 on 2026-07-20 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_rule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('user', 'month')},
        ),
    ]
