# Generated by Django 6.0.5 on 2026-07-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('stage_assigned', 'Stage assigned'), ('stage_done', 'Stage done'), ('salary', 'Salary')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_via_telegram', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
